include_recipe 'dev-env::jdk'
include_recipe 'dev-env::maven'
include_recipe 'dev-env::vagrant'
#include_recipe 'dev-env::repos'
include_recipe 'dev-env::idea'
include_recipe 'dev-env::infrastructure'
