# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "1"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.define :s1 do |box|
    box.vm.customize ["modifyvm", :id, "--memory", 1740]
    box.vm.network :hostonly, "10.0.0.2"
  end
  config.vm.define :s2 do |box|
    box.vm.customize ["modifyvm", :id, "--memory", 1740]
    box.vm.network :hostonly, "10.0.0.3"
  end
  config.vm.define :m1 do |box|
    box.vm.customize ["modifyvm", :id, "--memory", 3480]
    box.vm.network :hostonly, "10.0.0.4"
  end
  config.vm.define :m2 do |box|
    box.vm.customize ["modifyvm", :id, "--memory", 3480]
    box.vm.network :hostonly, "10.0.0.5"
  end
  config.vm.define :m3 do |box|
    box.vm.customize ["modifyvm", :id, "--memory", 3480]
    box.vm.network :hostonly, "10.0.0.6"
  end
  config.vm.define :l1 do |box|
    box.vm.customize ["modifyvm", :id, "--memory", 7000]
    box.vm.network :hostonly, "10.0.0.7"
  end
  config.vm.define :l2 do |box|
    box.vm.customize ["modifyvm", :id, "--memory", 7000]
    box.vm.network :hostonly, "10.0.0.8"
  end
  config.vm.define :l3 do |box|
    box.vm.customize ["modifyvm", :id, "--memory", 7000]
    box.vm.network :hostonly, "10.0.0.9"
  end

  config.vm.define :ci do |box|
    box.vm.customize ["modifyvm", :id, "--memory", 2560]
    box.vm.network :hostonly, "10.0.0.100"
  end

end
